plugins:
  discourse_add_to_summary_enabled:
    default: true
    client: true
  discourse_add_to_summary_before_header_topic_id:
    default: ""
    client: true
  discourse_add_to_summary_before_header_css:
    default: ""
    client: true
  discourse_add_to_summary_after_header_topic_id:
    default: ""
    client: true
  discourse_add_to_summary_after_header_css:
    default: ""
    client: true
