plugins:
  discourse_add_to_summary_enabled:
    default: true
    client: true
  add_to_before_header_topic_id:
    default: ""
    client: true
  add_to_before_header_css:
    default: ""
    client: true
  add_to_after_header_topic_id:
    default: ""
    client: true
  add_to_after_header_css:
    default: ""
    client: true
